services:
  db:
    image: "postgres:16-alpine"
    network_mode: "host"
    env_file:
      - .env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 5
  app:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    network_mode: "host"
    build: .
    env_file:
      - .env