apiVersion: apps/v1
kind: Deployment
metadata:
  name: home_telemetry_app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: home_telemetry
    spec:
      containers:
        - name: home_telemetry_app
          image: home_telemetry
          imagePullPolicy: "IfNotPresent"
          env:
              - name: DATABASE
                valueFrom:
                  configMapKeyRef:
                    key: DATABASE
                    name: home-telemetry-config
              - name: HEISHAMON_IP_ADDRESS
                valueFrom:
                  configMapKeyRef:
                    key: HEISHAMON_IP_ADDRESS
                    name: home-telemetry-config
              - name: P1_IP_ADDRESS
                valueFrom:
                  configMapKeyRef:
                    key: P1_IP_ADDRESS
                    name: home-telemetry-config
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_DB
                    name: home-telemetry-config
              - name: POSTGRES_HOST
                valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_HOST
                    name: home-telemetry-config
              - name: POSTGRES_PASSWORD
                valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_PASSWORD
                    name: home-telemetry-config
              - name: POSTGRES_PORT
                valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_PORT
                    name: home-telemetry-config
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    key: POSTGRES_USER
                    name: home-telemetry-config
              - name: SOLAX_SERIAL_NUMBER
                valueFrom:
                  configMapKeyRef:
                    key: SOLAX_SERIAL_NUMBER
                    name: home-telemetry-config
              - name: SOLAX_TOKEN_ID
                valueFrom:
                  configMapKeyRef:
                    key: SOLAX_TOKEN_ID
                    name: home-telemetry-config
